# Generated by Django 4.2.23 on 2025-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_accounts", "0004_alter_account_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="The name of the organization",
                max_length=200,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="accountinvitation",
            name="invitee_identifier",
            field=models.CharField(
                help_text="The contact identifier for the invitee, email, phone number, social media handle, etc.",
                max_length=1000,
                verbose_name="Invitee identifier",
            ),
        ),
    ]
