# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import organizations.base


class Migration(migrations.Migration):

    dependencies = [
        ('test_vendors', '0002_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_invites', to='test_vendors.Vendor')),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_vendors_vendorinvitation', to='test_vendors.VendorUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
    ]
